services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/data
      - $HOME/sep-rep-learning:/sep-rep-learning
    ports:
      - "8889:8080"
